spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.35.3:3306/video_parse?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    druid:
      min-idle: 3
      initial-size: 3
      max-wait: 30000
      validation-query: select 1 from dual
      test-on-borrow: true
  thymeleaf:
    mode: HTML5

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 3
    host: 192.168.35.3
    port: 6378
    client-name: video
    password:
  cache:
    type: redis
  profiles:
    active:

mybatis-plus:
  type-aliases-package: com.example.videoparse.entity
server:
  port: 12345

---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.35.3:3306/video_parse?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    druid:
      min-idle: 3
      initial-size: 3
      max-wait: 30000
      validation-query: select 1 from dual
      test-on-borrow: true
  thymeleaf:
    mode: HTML5

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 3
    host: 192.168.35.3
    port: 6378
    client-name: video
  cache:
    type: redis

mybatis-plus:
  type-aliases-package: com.example.videoparse.entity
server:
  port: 12345

---
spring:
  profiles: prod
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/video_parse?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    druid:
      min-idle: 3
      initial-size: 3
      max-wait: 30000
      validation-query: select 1 from dual
      test-on-borrow: true
  thymeleaf:
    mode: HTML5

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 3
    host: 127.0.0.1
    client-name: video
    password: 1221122
  cache:
    type: redis
mybatis-plus:
  type-aliases-package: com.example.videoparse.entity
server:
  port: 802

